-- CreateEnum
CREATE TYPE "SchoolMileageType" AS ENUM ('REWARD', 'PENALTY');

-- CreateTable
CREATE TABLE "school_mileage_rules" (
    "id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "type" "SchoolMileageType" NOT NULL,
    "category" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "default_score" INTEGER NOT NULL,
    "display_order" INTEGER NOT NULL,
    "is_active" BOOLEAN NOT NULL DEFAULT true,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "school_mileage_rules_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "school_mileage_entries" (
    "id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "student_id" TEXT NOT NULL,
    "rule_id" INTEGER NOT NULL,
    "type" "SchoolMileageType" NOT NULL,
    "score" INTEGER NOT NULL,
    "reason" TEXT,
    "awarded_at" TIMESTAMP(3) NOT NULL,
    "created_by_teacher_id" TEXT NOT NULL,
    "updated_by_teacher_id" TEXT,
    "deleted_by_teacher_id" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,
    "deleted_at" TIMESTAMP(3),

    CONSTRAINT "school_mileage_entries_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "school_mileage_rules_type_category_name_key" ON "school_mileage_rules"("type", "category", "name");

-- CreateIndex
CREATE INDEX "school_mileage_rules_is_active_display_order_idx" ON "school_mileage_rules"("is_active", "display_order");

-- CreateIndex
CREATE INDEX "school_mileage_entries_student_id_deleted_at_awarded_at_idx" ON "school_mileage_entries"("student_id", "deleted_at", "awarded_at");

-- CreateIndex
CREATE INDEX "school_mileage_entries_type_deleted_at_awarded_at_idx" ON "school_mileage_entries"("type", "deleted_at", "awarded_at");

-- CreateIndex
CREATE INDEX "school_mileage_entries_deleted_at_awarded_at_idx" ON "school_mileage_entries"("deleted_at", "awarded_at");

-- AddForeignKey
ALTER TABLE "school_mileage_entries" ADD CONSTRAINT "school_mileage_entries_student_id_fkey" FOREIGN KEY ("student_id") REFERENCES "students"("student_id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "school_mileage_entries" ADD CONSTRAINT "school_mileage_entries_rule_id_fkey" FOREIGN KEY ("rule_id") REFERENCES "school_mileage_rules"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "school_mileage_entries" ADD CONSTRAINT "school_mileage_entries_created_by_teacher_id_fkey" FOREIGN KEY ("created_by_teacher_id") REFERENCES "teachers"("teacher_id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "school_mileage_entries" ADD CONSTRAINT "school_mileage_entries_updated_by_teacher_id_fkey" FOREIGN KEY ("updated_by_teacher_id") REFERENCES "teachers"("teacher_id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "school_mileage_entries" ADD CONSTRAINT "school_mileage_entries_deleted_by_teacher_id_fkey" FOREIGN KEY ("deleted_by_teacher_id") REFERENCES "teachers"("teacher_id") ON DELETE SET NULL ON UPDATE CASCADE;

-- Seed school mileage rules
INSERT INTO "school_mileage_rules" ("type", "category", "name", "default_score", "display_order", "updated_at")
VALUES
    ('REWARD', '교내 환경', '봉사활동으로 교내 청소를 열심히 한 학생', 2, 1, CURRENT_TIMESTAMP),
    ('REWARD', '교내 환경', '솔선수범하여 학급 청소를 하거나, 학급 비품 관리, 쓰레기 분리수거 등을 잘한 학생', 2, 2, CURRENT_TIMESTAMP),
    ('REWARD', '교내 환경', '솔선수범하여 바닥에 떨어진 쓰레기를 자주 줍는 학생', 2, 3, CURRENT_TIMESTAMP),
    ('REWARD', '명예 표창', '학교 홍보에 열심히 참여한 학생', 5, 4, CURRENT_TIMESTAMP),
    ('REWARD', '명예 표창', '프로그램 개발을 통한 학교 발전 및 학생 생활에 도움을 준 학생', 10, 5, CURRENT_TIMESTAMP),
    ('REWARD', '선행 질서', '분실된 교구, 분실물을 습득 및 신고를 하여 타의 모범이 된 학생', 2, 6, CURRENT_TIMESTAMP),
    ('REWARD', '선행 질서', '벌점 규정 항목 대상 학생을 신고한 학생', 2, 7, CURRENT_TIMESTAMP),
    ('REWARD', '선행 질서', '어려운 상황에 처한 친구를 제보하여 위험을 모면하게 도와준 학생', 5, 8, CURRENT_TIMESTAMP),
    ('REWARD', '선행 질서', '선행, 효행, 단체 활동, 불우이웃돕기, 일손 돕기 등의 봉사활동을 하여 공인된 외부기관에서 모범 표창을 받은 경우', 10, 9, CURRENT_TIMESTAMP),
    ('REWARD', '선행 질서', '타인을 위해 희생, 봉사적 활동을 한 학생', 3, 10, CURRENT_TIMESTAMP),
    ('REWARD', '수업 관련', '학습활동과 기본생활 영역에서 모범이 되는 행동을 하여 추천을 받은 학생', 2, 11, CURRENT_TIMESTAMP),
    ('REWARD', '수업 관련', '수업 시간에 바른 태도로 타의 모범이 된 학생', 2, 12, CURRENT_TIMESTAMP),
    ('REWARD', '수업 관련', '수업에서 교재, 교구, 기자재 관리 및 안전 관리에 모범적인 행동을 한 학생', 2, 13, CURRENT_TIMESTAMP),
    ('REWARD', '수업 관련', '학습 준비물을 철저히 준비하여 수업 보조 도구로 활용되도록 한 학생', 2, 14, CURRENT_TIMESTAMP),
    ('REWARD', '학교 활동', '교사의 교육활동에 도움을 주는 학생', 1, 15, CURRENT_TIMESTAMP),
    ('REWARD', '학교 활동', '행사도우미, 학교행사 활동 등 교사의 교육활동에 적극적으로 도움을 주는 학생', 2, 16, CURRENT_TIMESTAMP),
    ('REWARD', '학교 활동', '특별실 관리 또는 학교, 학급 활동에 모범이 되어 담당 교사의 추천을 받은 학생', 3, 17, CURRENT_TIMESTAMP),
    ('REWARD', '학교 활동', '학교 행사 후 청소 및 정리정돈에 솔선수범하여 참여한 학생', 10, 18, CURRENT_TIMESTAMP),
    ('PENALTY', '교내 생활', '가벼운 교육적 지시 사항을 어긴 학생', 1, 19, CURRENT_TIMESTAMP),
    ('PENALTY', '교내 생활', '교사의 교육적인 지시 내용을 지속적으로 불이행한 학생', 10, 20, CURRENT_TIMESTAMP),
    ('PENALTY', '교내 생활', '소란행위를 한 학생 (고성, 괴성, 음악 크게 틀기, 복도에서 달리기 등)', 2, 21, CURRENT_TIMESTAMP),
    ('PENALTY', '교내 생활', '쓰레기(음식물 포함)등을 교내 아무 곳에나 버리는 학생', 2, 22, CURRENT_TIMESTAMP),
    ('PENALTY', '교내 생활', '교내에서 껌이나 침을 아무데나 뱉거나 버리는 학생', 2, 23, CURRENT_TIMESTAMP),
    ('PENALTY', '교내 생활', '급식실에서 질서를 지키지 않고 새치기를 하는 학생', 2, 24, CURRENT_TIMESTAMP),
    ('PENALTY', '교내 생활', '책·걸상, 학교 벽 등 학교 시설에 낙서를 한 학생', 2, 25, CURRENT_TIMESTAMP),
    ('PENALTY', '교내 생활', '청소 활동에 이유 없이 불참한 학생', 2, 26, CURRENT_TIMESTAMP),
    ('PENALTY', '교내 생활', '상습적으로 욕설 및 폭언, 음담패설 등을 하여 주변에 피해를 주는 학생', 2, 27, CURRENT_TIMESTAMP),
    ('PENALTY', '교내 생활', '교내,외에서 이성 간 풍기 문란한 행동을 한 학생', 5, 28, CURRENT_TIMESTAMP),
    ('PENALTY', '교내 생활', '고데기 등 화재 위험성이 있는 전열기 소지 및 사용한 학생', 10, 29, CURRENT_TIMESTAMP),
    ('PENALTY', '교내 생활', '불법사이트(토토 등), 화투, 카드 등을 이용하여 도박을 한 학생', 20, 30, CURRENT_TIMESTAMP),
    ('PENALTY', '교내 생활', '원동기나 차량을 운전해서 등·하교한 학생', 10, 31, CURRENT_TIMESTAMP),
    ('PENALTY', '교내 생활', '교내 외 시설물, 차량 또는 물품을 고의로 파손한 학생', 20, 32, CURRENT_TIMESTAMP),
    ('PENALTY', '교내 생활', '본인의 교실 외 타학년 및 타교실에 들어간 학생', 3, 33, CURRENT_TIMESTAMP),
    ('PENALTY', '교내 생활', '급식실 외 공간(교실, 실습실, 복도)에서 간식 먹는 학생', 3, 34, CURRENT_TIMESTAMP),
    ('PENALTY', '교내 생활', '체육관 음식물 반입 금지를 어긴 학생', 3, 35, CURRENT_TIMESTAMP),
    ('PENALTY', '교내 생활', '교실 내 개인 물품이나 택배 상자 등을 방치하여 다른 학생에게 피해를 주는 학생', 3, 36, CURRENT_TIMESTAMP),
    ('PENALTY', '교내 생활', '허락없이 교내 엘리베이터를 탑승하다 적발된 학생', 2, 37, CURRENT_TIMESTAMP),
    ('PENALTY', '교외 생활', '출입이 금지된 구역(유흥업소 등)에 출입을 한 학생', 20, 38, CURRENT_TIMESTAMP),
    ('PENALTY', '교외 생활', '지역 주민, 경찰서 등으로부터 신고를 받은 학생', 10, 39, CURRENT_TIMESTAMP),
    ('PENALTY', '교외 생활', '무면허 운전(자동차, 원동기 등)신고접수 및 적발된 학생', 20, 40, CURRENT_TIMESTAMP),
    ('PENALTY', '교외 생활', '불미스러운 행동으로 학교의 명예를 훼손한 학생', 20, 41, CURRENT_TIMESTAMP),
    ('PENALTY', '스쿨 캠핑장', '스쿨 캠핑장 이용 시 기구 및 장소 청소 등 정리 정돈을 제대로 하지 않은 학생', 3, 42, CURRENT_TIMESTAMP),
    ('PENALTY', '스쿨 캠핑장', '스쿨 캠핑장 물품을 파손한 학생', 5, 43, CURRENT_TIMESTAMP),
    ('PENALTY', '스쿨 캠핑장', '스쿨 캠핑장 이용 신청 외 학생이 이용할 경우', 5, 44, CURRENT_TIMESTAMP),
    ('PENALTY', '야간 자습 시간', '야간 자습 시간에 핸드폰, 노트북 등을 사용하여 게임을 하는 학생', 5, 45, CURRENT_TIMESTAMP),
    ('PENALTY', '야간 자습 시간', '야간 자습 시간에 학습 활동 외 활동(음악 크게 틀어서 듣기, 영상보며 떠들기, 잡담, 욕설 등)으로 주변 사람에게 피해를 주는 학생', 5, 46, CURRENT_TIMESTAMP),
    ('PENALTY', '야간 자습 시간', '야간 자습 시간에 허락 없이 돌아다니는 학생', 3, 47, CURRENT_TIMESTAMP),
    ('PENALTY', '야간 자습 시간', '야간 자습 시간에 지정된 공부 장소 외 공간에 허락 없이 있는 학생', 3, 48, CURRENT_TIMESTAMP),
    ('PENALTY', '야간 자습 시간', '야간 자습 시간에 음식물을 취식하는 학생', 2, 49, CURRENT_TIMESTAMP),
    ('PENALTY', '야간 자습 시간', '야간 자습 시간 시작 후(19:10) 늦게 교실에 입실하는 학생', 2, 50, CURRENT_TIMESTAMP),
    ('PENALTY', '야간 자습 시간', '야간 자습 시간에 허락 없이 자리를 바꿔 앉는 학생', 2, 51, CURRENT_TIMESTAMP),
    ('PENALTY', '용의복장', '복장 규정을 위반한 학생(넥타이 미착용)', 1, 52, CURRENT_TIMESTAMP),
    ('PENALTY', '용의복장', '액세서리(귀걸이)를 착용한 학생 (투명, 단순 귀걸이 허용)', 2, 53, CURRENT_TIMESTAMP),
    ('PENALTY', '용의복장', '용의 규정을 위반한 학생(염색)', 5, 54, CURRENT_TIMESTAMP),
    ('PENALTY', '용의복장', '문신을 가리지 않은 학생', 5, 55, CURRENT_TIMESTAMP),
    ('PENALTY', '용의복장', '재학 기간 중 문신을 한 학생', 30, 56, CURRENT_TIMESTAMP),
    ('PENALTY', '용의복장', '복장 규정을 위반한 학생(셔츠, 바지 미착용)', 2, 57, CURRENT_TIMESTAMP),
    ('PENALTY', '출결 수업', '정규/방과 후 수업 중 태도 불량 학생(수면)', 3, 58, CURRENT_TIMESTAMP),
    ('PENALTY', '출결 수업', '정규/방과 후 수업 중 태도 불량 학생(교과서, 준비물 미지참, 과제 불이행)', 5, 59, CURRENT_TIMESTAMP),
    ('PENALTY', '출결 수업', '정규/방과 후 수업 중 태도 불량 학생(잡담, 욕설, 수업 방해)', 5, 60, CURRENT_TIMESTAMP),
    ('PENALTY', '출결 수업', '정규/방과 후 수업 시간 중 음식물을 취식한 학생', 4, 61, CURRENT_TIMESTAMP),
    ('PENALTY', '출결 수업', '정규/방과 후 수업 시간 중 화장행위를 한 학생', 5, 62, CURRENT_TIMESTAMP),
    ('PENALTY', '출결 수업', '정규/방과 후 수업 시간 중 전자기기(핸드폰, 노트북, 웨어러블기기)를 사용 및 미제출한 학생', 10, 63, CURRENT_TIMESTAMP),
    ('PENALTY', '출결 수업', '정규/방과 후 수업 종료 전 퇴실한 학생', 4, 64, CURRENT_TIMESTAMP),
    ('PENALTY', '출결 수업', '정규/방과 후 수업 미인정 외출, 지각(5분 이상), 화장실(10분 이상), 결과를 한 학생', 3, 65, CURRENT_TIMESTAMP),
    ('PENALTY', '출결 수업', '정규/방과 후 수업 미인정 결석 및 조퇴를 한 학생', 5, 66, CURRENT_TIMESTAMP),
    ('PENALTY', '출결 수업', '정규/방과 후 수업 시간 중 SNS(카카오 등)를 이용하여 대화를 주고 받는 것을 적발당한 학생', 3, 67, CURRENT_TIMESTAMP),
    ('PENALTY', '출결 수업', '조례시간(08:30~08:40)에 지각한 학생', 2, 68, CURRENT_TIMESTAMP),
    ('PENALTY', '흡연 음주 약물', '담배, 라이터, 음란물 등 소지 금지 물품을 소지한 학생', 10, 69, CURRENT_TIMESTAMP),
    ('PENALTY', '흡연 음주 약물', '교내·외에서 흡연이나 음주를 한 학생', 20, 70, CURRENT_TIMESTAMP),
    ('PENALTY', '흡연 음주 약물', '의학적 목적이 아닌 약물을 소지하거나 복용 및 흉기를 소지한 학생', 20, 71, CURRENT_TIMESTAMP);
