-- AlterTable: teachers에 is_dorm_teacher 컬럼 추가
ALTER TABLE "teachers" ADD COLUMN "is_dorm_teacher" BOOLEAN NOT NULL DEFAULT false;

-- CreateEnum
CREATE TYPE "DormMileageType" AS ENUM ('REWARD', 'PENALTY');

-- CreateTable
CREATE TABLE "dorm_mileage_rules" (
    "id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "type" "DormMileageType" NOT NULL,
    "category" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "default_score" INTEGER NOT NULL,
    "min_score" INTEGER,
    "max_score" INTEGER,
    "display_order" INTEGER NOT NULL,
    "is_active" BOOLEAN NOT NULL DEFAULT true,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "dorm_mileage_rules_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "dorm_mileage_entries" (
    "id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "student_id" TEXT NOT NULL,
    "rule_id" INTEGER NOT NULL,
    "type" "DormMileageType" NOT NULL,
    "score" INTEGER NOT NULL,
    "reason" TEXT,
    "awarded_at" TIMESTAMP(3) NOT NULL,
    "created_by_teacher_id" TEXT NOT NULL,
    "updated_by_teacher_id" TEXT,
    "deleted_by_teacher_id" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,
    "deleted_at" TIMESTAMP(3),

    CONSTRAINT "dorm_mileage_entries_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "dorm_mileage_rules_type_category_name_key" ON "dorm_mileage_rules"("type", "category", "name");

-- CreateIndex
CREATE INDEX "dorm_mileage_rules_is_active_display_order_idx" ON "dorm_mileage_rules"("is_active", "display_order");

-- CreateIndex
CREATE INDEX "dorm_mileage_entries_student_id_deleted_at_awarded_at_idx" ON "dorm_mileage_entries"("student_id", "deleted_at", "awarded_at");

-- CreateIndex
CREATE INDEX "dorm_mileage_entries_type_deleted_at_awarded_at_idx" ON "dorm_mileage_entries"("type", "deleted_at", "awarded_at");

-- CreateIndex
CREATE INDEX "dorm_mileage_entries_deleted_at_awarded_at_idx" ON "dorm_mileage_entries"("deleted_at", "awarded_at");

-- AddForeignKey
ALTER TABLE "dorm_mileage_entries" ADD CONSTRAINT "dorm_mileage_entries_student_id_fkey" FOREIGN KEY ("student_id") REFERENCES "students"("student_id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "dorm_mileage_entries" ADD CONSTRAINT "dorm_mileage_entries_rule_id_fkey" FOREIGN KEY ("rule_id") REFERENCES "dorm_mileage_rules"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "dorm_mileage_entries" ADD CONSTRAINT "dorm_mileage_entries_created_by_teacher_id_fkey" FOREIGN KEY ("created_by_teacher_id") REFERENCES "teachers"("teacher_id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "dorm_mileage_entries" ADD CONSTRAINT "dorm_mileage_entries_updated_by_teacher_id_fkey" FOREIGN KEY ("updated_by_teacher_id") REFERENCES "teachers"("teacher_id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "dorm_mileage_entries" ADD CONSTRAINT "dorm_mileage_entries_deleted_by_teacher_id_fkey" FOREIGN KEY ("deleted_by_teacher_id") REFERENCES "teachers"("teacher_id") ON DELETE SET NULL ON UPDATE CASCADE;

-- Seed dorm mileage rules
INSERT INTO "dorm_mileage_rules" ("type", "category", "name", "default_score", "min_score", "max_score", "display_order", "updated_at")
VALUES
    ('REWARD', '기숙사 생활', '깨끗한 호실을 유지하는 호실 학생 전원', 3, NULL, NULL, 1, CURRENT_TIMESTAMP),
    ('REWARD', '기숙사 생활', '생활관 내 생활이 타의 모범이 되는 자', 2, 2, 5, 2, CURRENT_TIMESTAMP),
    ('REWARD', '기숙사 생활', '건물 내의 환경 미화 및 공공 시설물에서의 노력 봉사자', 1, 1, 3, 3, CURRENT_TIMESTAMP),
    ('REWARD', '기숙사 생활', '위 사항에 없는 사안 (운영위원회 협의)', 1, 1, 5, 4, CURRENT_TIMESTAMP),
    ('REWARD', '신고', '신고 (분실물 습득)', 1, NULL, NULL, 5, CURRENT_TIMESTAMP),
    ('REWARD', '신고', '신고 (사내 기물 파손)', 1, NULL, NULL, 6, CURRENT_TIMESTAMP),
    ('REWARD', '신고', '신고 (흡연, 음주 및 규정 위반)', 2, NULL, NULL, 7, CURRENT_TIMESTAMP),
    ('REWARD', '신고', '신고 (폭력, 금품 갈취)', 3, NULL, NULL, 8, CURRENT_TIMESTAMP),
    ('REWARD', '자치회 임원', '자치회 임원 (층장 포함) 및 봉사자 (학기당)', 3, NULL, NULL, 9, CURRENT_TIMESTAMP),
    ('PENALTY', '기숙사 규정', '정해진 호실 이외에서 숙박하는 행위', 20, NULL, NULL, 10, CURRENT_TIMESTAMP),
    ('PENALTY', '기숙사 규정', '무단 외출', 20, NULL, NULL, 11, CURRENT_TIMESTAMP),
    ('PENALTY', '기숙사 규정', '도박 행위 (고리대금 행위 포함)', 20, NULL, NULL, 12, CURRENT_TIMESTAMP),
    ('PENALTY', '기숙사 규정', '흡연·음주·도박행위 동조', 20, NULL, NULL, 13, CURRENT_TIMESTAMP),
    ('PENALTY', '기숙사 규정', '야간 자율시간 야간 출입 제한 구역 출입', 15, NULL, NULL, 14, CURRENT_TIMESTAMP),
    ('PENALTY', '기숙사 규정', '흡연 도구 소지', 15, NULL, NULL, 15, CURRENT_TIMESTAMP),
    ('PENALTY', '기숙사 규정', '음란 서적·동영상 소유 또는 유포', 10, NULL, NULL, 16, CURRENT_TIMESTAMP),
    ('PENALTY', '기숙사 규정', '사감 및 기숙사 담당 교사 지시 불이행', 10, NULL, NULL, 17, CURRENT_TIMESTAMP),
    ('PENALTY', '기숙사 규정', '타인의 음식을 훔쳐 먹거나 물건을 무단 사용', 10, NULL, NULL, 18, CURRENT_TIMESTAMP),
    ('PENALTY', '기숙사 규정', '기숙사 내외 시설 및 물품 고의 파손', 10, NULL, NULL, 19, CURRENT_TIMESTAMP),
    ('PENALTY', '기숙사 규정', '빈 타호실 출입', 10, NULL, NULL, 20, CURRENT_TIMESTAMP),
    ('PENALTY', '기숙사 규정', '취침 시간 이후 타인 수면 방해', 5, NULL, NULL, 21, CURRENT_TIMESTAMP),
    ('PENALTY', '기숙사 규정', '점호 이후 기숙사 내 이동 또는 타 호실 출입', 5, NULL, NULL, 22, CURRENT_TIMESTAMP),
    ('PENALTY', '기숙사 규정', '허락 없이 포장 음식 반입', 5, NULL, NULL, 23, CURRENT_TIMESTAMP),
    ('PENALTY', '기숙사 규정', '허락되지 않은 전열 기구 사용', 5, NULL, NULL, 24, CURRENT_TIMESTAMP),
    ('PENALTY', '기숙사 규정', '공용 공간 쓰레기 투기 및 분리수거 미이행', 5, NULL, NULL, 25, CURRENT_TIMESTAMP),
    ('PENALTY', '기숙사 규정', '소란한 행위로 타인에게 피해', 5, NULL, NULL, 26, CURRENT_TIMESTAMP),
    ('PENALTY', '기숙사 규정', '야간 자율 시간 미준수', 5, NULL, NULL, 27, CURRENT_TIMESTAMP),
    ('PENALTY', '기숙사 규정', '몰입실 사용 시간 미준수', 5, NULL, NULL, 28, CURRENT_TIMESTAMP),
    ('PENALTY', '기숙사 규정', '허락되지 않은 공간에서 음식 섭취', 5, NULL, NULL, 29, CURRENT_TIMESTAMP),
    ('PENALTY', '기숙사 규정', '취식 후 뒷정리 미이행', 5, NULL, NULL, 30, CURRENT_TIMESTAMP),
    ('PENALTY', '기숙사 규정', '몰입실(랩실) 면학 분위기 저해', 3, NULL, NULL, 31, CURRENT_TIMESTAMP),
    ('PENALTY', '기숙사 규정', '몰입실(랩실)에서 학습 이외의 활동', 3, NULL, NULL, 32, CURRENT_TIMESTAMP),
    ('PENALTY', '기숙사 규정', '기숙사 내에서 소란 (속옷 착용 등)', 3, NULL, NULL, 33, CURRENT_TIMESTAMP),
    ('PENALTY', '기숙사 규정', '아침 퇴실 시간 미준수', 5, NULL, NULL, 34, CURRENT_TIMESTAMP),
    ('PENALTY', '기숙사 규정', '소등 시간 이후 점등 (호실원 전체)', 3, NULL, NULL, 35, CURRENT_TIMESTAMP),
    ('PENALTY', '기숙사 규정', '허락되지 않은 시간에 기숙사 무단 입실', 3, NULL, NULL, 36, CURRENT_TIMESTAMP),
    ('PENALTY', '기숙사 규정', '침구 상태 및 사물 정리 정돈 불량', 3, NULL, NULL, 37, CURRENT_TIMESTAMP),
    ('PENALTY', '기숙사 규정', '세탁물 수거 지연 또는 공용 물건 방치', 3, NULL, NULL, 38, CURRENT_TIMESTAMP),
    ('PENALTY', '기숙사 규정', '냉장고 및 전자레인지 불량 사용', 3, NULL, NULL, 39, CURRENT_TIMESTAMP),
    ('PENALTY', '기숙사 규정', '인원 점검 시 지각', 3, NULL, NULL, 40, CURRENT_TIMESTAMP),
    ('PENALTY', '기숙사 규정', '허위 신고', 3, NULL, NULL, 41, CURRENT_TIMESTAMP);
